# Generated by Django 5.1.4 on 2024-12-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Availability', 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': 'Event Participant', 'verbose_name_plural': 'Event Participants'},
        ),
        migrations.CreateModel(
            name='AvailableUsersForEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_users', models.ManyToManyField(related_name='available_for_events', through='meetings.Availability', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.event')),
            ],
            options={
                'verbose_name': 'Available Users For Event',
                'verbose_name_plural': 'Available Users For Events',
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='meetings.availableusersforevent'),
            preserve_default=False,
        ),
    ]
