# Generated by Django 5.1.4 on 2024-12-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_event_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
